# Generated by Django 3.2.9 on 2021-11-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registration_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration_table',
        ),
    ]
